### PR TITLE
feat: Add Contact Section, Footer Component, Scroll-to-Top Button & Fix Course Card Height Consistency

### LINKED ISSUE #14: UI Inconsistency in Course Cards + Missing Footer and Scroll-to-Top Button
📌 Issue Summary:
The course cards displayed on the course section have unequal heights, which breaks the visual balance of the UI. Some cards appear taller than others due to varying content length. Along with this, the following sections are missing or incomplete:

🔍 Problems Observed:
Inconsistent Card Height

All cards should be of equal height for a clean and consistent look.

Current variation affects the user experience and layout symmetry.

Missing Footer Section

The website does not include a footer.

A footer can contain useful links like About Us, Contact, Terms, and Social Media.

No Contact Section

There is no dedicated contact form or section for users to reach out.

This limits user engagement and feedback collection.

Missing “Back to Top” Button

Scrolling back to the top is inconvenient on long pages.

Adding a floating scroll-to-top button improves navigation and usability.

💡 Suggestions:
Use Flexbox or CSS Grid to ensure all cards maintain the same height.

Add a simple footer component with minimal links and design.

Implement a contact section (with a form or email) at the bottom of the page.

Add a scroll-to-top button that appears after a certain scroll distance.

🙋‍♂️ Contributor Note:
I would love to work on this issue as a Level 3 GSSoC'25 Contributor. I'm confident I can fix these UI problems and improve the overall design. Kindly assign this issue to me.

Image

### PR DESCRIPTION
**Pull request by Adarshnayak21**
📝 2. Description
This pull request enhances the UI/UX of the CourseHub project and resolves layout inconsistencies. It introduces new sections (Contact, Footer, Scroll-to-Top) and addresses a UI bug related to course card height mismatch.

These changes aim to improve the visual consistency, user navigation, and overall structure of the platform for both desktop and mobile users.

🔗 3. Related Issues
Closes #14

🛠 4. Changes Made
 Added Footer Component (components/Footer.tsx)

Contains centered branding text and aligned social media icons

Responsive across devices

 Created ScrollToTopButton Component (components/ScrollToTopButton.tsx)

Appears on scroll and smoothly scrolls back to top

Positioned above the footer, doesn't overlap content

 Implemented Contact Section (pages/Contact.tsx)

Includes Name, Email, and Message input fields

Proper alignment and responsiveness

 Fixed Inconsistent Course Card Heights

Applied uniform card height styling

Ensures consistent look on Courses page

 Integrated all new components into the App structure

Footer and ScrollToTop added in App.tsx

✅ 5. Checklist
 I have read the project's contributing guidelines.

 My code follows the project's coding style and conventions.

 I have performed a thorough self-review of my own code.

 I have added comments where needed.

 My changes introduce no new warnings or errors.

 All UI components render correctly across major viewports.

 I’ve linked this PR to the appropriate issue using Closes #14.

### CODE REVIEW

File: Front/src/pages/Home.tsx [hunk 1]
```diff
@@ -138,6 +139,36 @@ const Home: React.FC = () => {
           </Link>
         </div>
       </section>
+
+      {/* Contact Section */}
+      <section className="bg-white py-16 border-t">
```
Comment (hudazaan) [inline Front/src/pages/Home.tsx:144]: reduce contact section padding.
